/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-12-20 07:47:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("        ");
 User loggedInUser=(User) session.getAttribute("user"); String userRole=loggedInUser !=null ?
            loggedInUser.getRole() : "user" ; boolean isAdmin="admin" .equals(userRole); 
      out.write("\n");
      out.write("            <!DOCTYPE html>\n");
      out.write("            <html>\n");
      out.write("\n");
      out.write("            <head>\n");
      out.write("                <title>MoneyMate Dashboard</title>\n");
      out.write("                <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("                <style>\n");
      out.write("                    .user-info {\n");
      out.write("                        display: flex;\n");
      out.write("                        align-items: center;\n");
      out.write("                        gap: 1rem;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .user-badge {\n");
      out.write("                        display: flex;\n");
      out.write("                        align-items: center;\n");
      out.write("                        gap: 0.5rem;\n");
      out.write("                        background: rgba(79, 70, 229, 0.1);\n");
      out.write("                        padding: 0.5rem 1rem;\n");
      out.write("                        border-radius: 50px;\n");
      out.write("                        font-size: 0.9rem;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .user-name {\n");
      out.write("                        font-weight: 600;\n");
      out.write("                        color: var(--primary);\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .user-role {\n");
      out.write("                        font-size: 0.75rem;\n");
      out.write("                        text-transform: uppercase;\n");
      out.write("                        background: var(--primary);\n");
      out.write("                        color: white;\n");
      out.write("                        padding: 0.15rem 0.5rem;\n");
      out.write("                        border-radius: 50px;\n");
      out.write("                        font-weight: 700;\n");
      out.write("                        letter-spacing: 0.05em;\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .btn-logout {\n");
      out.write("                        background: linear-gradient(135deg, var(--danger), #dc2626);\n");
      out.write("                        color: white;\n");
      out.write("                        padding: 0.5rem 1rem;\n");
      out.write("                        border-radius: var(--radius-md);\n");
      out.write("                        text-decoration: none;\n");
      out.write("                        font-weight: 600;\n");
      out.write("                        font-size: 0.9rem;\n");
      out.write("                        transition: all 0.2s;\n");
      out.write("                        box-shadow: var(--shadow-sm);\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .btn-logout:hover {\n");
      out.write("                        transform: translateY(-2px);\n");
      out.write("                        box-shadow: var(--shadow-md);\n");
      out.write("                        filter: brightness(110%);\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .btn-profile {\n");
      out.write("                        background: linear-gradient(135deg, var(--primary), var(--primary-hover));\n");
      out.write("                        color: white;\n");
      out.write("                        padding: 0.5rem 1rem;\n");
      out.write("                        border-radius: var(--radius-md);\n");
      out.write("                        text-decoration: none;\n");
      out.write("                        font-weight: 600;\n");
      out.write("                        font-size: 0.9rem;\n");
      out.write("                        transition: all 0.2s;\n");
      out.write("                        box-shadow: var(--shadow-sm);\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                    .btn-profile:hover {\n");
      out.write("                        transform: translateY(-2px);\n");
      out.write("                        box-shadow: var(--shadow-md);\n");
      out.write("                        filter: brightness(110%);\n");
      out.write("                    }\n");
      out.write("                </style>\n");
      out.write("            </head>\n");
      out.write("\n");
      out.write("            <body>\n");
      out.write("                <nav class=\"navbar\">\n");
      out.write("                    <a href=\"index.jsp\" class=\"brand\">💰 MoneyMate</a>\n");
      out.write("                    <div class=\"user-info\">\n");
      out.write("                        <div class=\"user-badge\">\n");
      out.write("                            <span>👤</span>\n");
      out.write("                            <span class=\"user-name\">\n");
      out.write("                                ");
      out.print( loggedInUser.getNama() );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                            <span class=\"user-role\">\n");
      out.write("                                ");
      out.print( userRole );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                        <a href=\"ProfileServlet\" class=\"btn-profile\">👤 Profile</a>\n");
      out.write("                        <a href=\"LogoutServlet\" class=\"btn-logout\">Logout</a>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <!-- Hero Section -->\n");
      out.write("                    <div style=\"text-align: center; margin-bottom: 3rem; margin-top: 3rem;\">\n");
      out.write("                        <h1 style=\"font-size: 3rem; margin-bottom: 0.5rem; text-align: center;\">Welcome Back!</h1>\n");
      out.write("                        <p\n");
      out.write("                            style=\"color: var(--text-muted); font-size: 1.1rem; max-width: 600px; margin: 0 auto; text-align: center;\">\n");
      out.write("                            Kelola keuangan masa depanmu dengan lebih cerdas. Pantau pemasukan, tagihan, dan tabunganmu\n");
      out.write("                            di satu\n");
      out.write("                            tempat.\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- Dashboard Grid -->\n");
      out.write("                    <div class=\"menu-grid\">\n");
      out.write("                        <a href=\"TransaksiServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">💸</div>\n");
      out.write("                            <h3>Transaksi</h3>\n");
      out.write("                            <small>Catat Pemasukan & Pengeluaran</small>\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"AnggaranServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">📊</div>\n");
      out.write("                            <h3>Anggaran</h3>\n");
      out.write("                            <small>Atur Budget Bulanan</small>\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"LaporanServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">📈</div>\n");
      out.write("                            <h3>Laporan</h3>\n");
      out.write("                            <small>Ringkasan Keuangan</small>\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"TargetTabunganServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">🎯</div>\n");
      out.write("                            <h3>Target Tabungan</h3>\n");
      out.write("                            <small>Goals Anda</small>\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"TagihanServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">🧾</div>\n");
      out.write("                            <h3>Tagihan</h3>\n");
      out.write("                            <small>Jatuh Tempo</small>\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"PengingatServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">🔔</div>\n");
      out.write("                            <h3>Pengingat</h3>\n");
      out.write("                            <small>Reminder & Notes</small>\n");
      out.write("                        </a>\n");
      out.write("                        <a href=\"FinGoalServlet\" class=\"card menu-item\">\n");
      out.write("                            <div class=\"icon\">🏁</div>\n");
      out.write("                            <h3>FinGoal</h3>\n");
      out.write("                            <small>Progress Tracking</small>\n");
      out.write("                        </a>\n");
      out.write("\n");
      out.write("                        <!-- Admin Only Features -->\n");
      out.write("                        ");
 if (isAdmin) { 
      out.write("\n");
      out.write("                            <a href=\"KategoriServlet\" class=\"card menu-item\">\n");
      out.write("                                <div class=\"icon\">📂</div>\n");
      out.write("                                <h3>Kategori</h3>\n");
      out.write("                                <small>Master Data</small>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"UserServlet\" class=\"card menu-item\">\n");
      out.write("                                <div class=\"icon\">👥</div>\n");
      out.write("                                <h3>Users</h3>\n");
      out.write("                                <small>Kelola Pengguna</small>\n");
      out.write("                            </a>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div style=\"margin-top: 4rem; text-align: center; color: var(--text-muted); font-size: 0.9rem;\">\n");
      out.write("                        &copy; 2025 MoneyMate Financial System\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </body>\n");
      out.write("\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
