/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2025-12-20 09:23:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Login - MoneyMate</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                min-height: 100vh;\r\n");
      out.write("                padding: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-container {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                max-width: 450px;\r\n");
      out.write("                animation: fadeUp 0.6s ease-out;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-card {\r\n");
      out.write("                background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("                backdrop-filter: blur(16px);\r\n");
      out.write("                border: 1px solid rgba(255, 255, 255, 0.7);\r\n");
      out.write("                border-radius: var(--radius-lg);\r\n");
      out.write("                padding: 3rem;\r\n");
      out.write("                box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-header {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                margin-bottom: 2.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-icon {\r\n");
      out.write("                font-size: 4rem;\r\n");
      out.write("                margin-bottom: 1rem;\r\n");
      out.write("                display: block;\r\n");
      out.write("                filter: drop-shadow(0 4px 8px rgba(79, 70, 229, 0.3));\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-title {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("                margin-bottom: 0.5rem;\r\n");
      out.write("                background: linear-gradient(135deg, var(--primary), var(--accent));\r\n");
      out.write("                -webkit-background-clip: text;\r\n");
      out.write("                -webkit-text-fill-color: transparent;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .login-subtitle {\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("                font-size: 0.95rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .error-message {\r\n");
      out.write("                background: linear-gradient(135deg, #fee2e2, #fecaca);\r\n");
      out.write("                border: 1px solid #fca5a5;\r\n");
      out.write("                color: #991b1b;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                border-radius: var(--radius-md);\r\n");
      out.write("                margin-bottom: 1.5rem;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                animation: shake 0.4s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @keyframes shake {\r\n");
      out.write("\r\n");
      out.write("                0%,\r\n");
      out.write("                100% {\r\n");
      out.write("                    transform: translateX(0);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                25% {\r\n");
      out.write("                    transform: translateX(-10px);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                75% {\r\n");
      out.write("                    transform: translateX(10px);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group {\r\n");
      out.write("                margin-bottom: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form-group label {\r\n");
      out.write("                display: block;\r\n");
      out.write("                margin-bottom: 0.5rem;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-wrapper {\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .input-icon {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                left: 1rem;\r\n");
      out.write("                top: 50%;\r\n");
      out.write("                transform: translateY(-50%);\r\n");
      out.write("                font-size: 1.2rem;\r\n");
      out.write("                color: var(--text-muted);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            input[type=\"email\"],\r\n");
      out.write("            input[type=\"password\"] {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 0.875rem 1rem 0.875rem 3rem;\r\n");
      out.write("                background: white;\r\n");
      out.write("                border: 2px solid #e2e8f0;\r\n");
      out.write("                border-radius: var(--radius-md);\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("                color: var(--text);\r\n");
      out.write("                transition: all 0.2s;\r\n");
      out.write("                font-family: inherit;\r\n");
      out.write("                box-sizing: border-box;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            input:focus {\r\n");
      out.write("                outline: none;\r\n");
      out.write("                border-color: var(--primary);\r\n");
      out.write("                box-shadow: 0 0 0 4px rgba(79, 70, 229, 0.1);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                background: linear-gradient(135deg, var(--primary), var(--primary-hover));\r\n");
      out.write("                color: white;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: var(--radius-md);\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: all 0.2s;\r\n");
      out.write("                box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);\r\n");
      out.write("                margin-top: 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login:hover {\r\n");
      out.write("                transform: translateY(-2px);\r\n");
      out.write("                box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.2);\r\n");
      out.write("                filter: brightness(110%);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-login:active {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"login-container\">\r\n");
      out.write("            <div class=\"login-card\">\r\n");
      out.write("                <div class=\"login-header\">\r\n");
      out.write("                    <span class=\"login-icon\">💰</span>\r\n");
      out.write("                    <h1 class=\"login-title\">MoneyMate</h1>\r\n");
      out.write("                    <p class=\"login-subtitle\">Kelola keuangan Anda dengan lebih cerdas</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
 if (request.getAttribute("error") !=null) { 
      out.write("\r\n");
      out.write("                    <div class=\"error-message\">\r\n");
      out.write("                        ⚠️ ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <form method=\"post\" action=\"LoginServlet\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"email\">Email</label>\r\n");
      out.write("                                <div class=\"input-wrapper\">\r\n");
      out.write("                                    <span class=\"input-icon\">📧</span>\r\n");
      out.write("                                    <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"user@moneymate.com\"\r\n");
      out.write("                                        required autofocus>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"password\">Password</label>\r\n");
      out.write("                                <div class=\"input-wrapper\">\r\n");
      out.write("                                    <span class=\"input-icon\">🔒</span>\r\n");
      out.write("                                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"••••••••\"\r\n");
      out.write("                                        required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-login\">\r\n");
      out.write("                                Login 🚀\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <div\r\n");
      out.write("                            style=\"text-align: center; margin-top: 1.5rem; color: var(--text-muted); font-size: 0.9rem;\">\r\n");
      out.write("                            Belum punya akun? <a href=\"RegisterServlet\"\r\n");
      out.write("                                style=\"color: var(--primary); font-weight: 600; text-decoration: none;\">Daftar di\r\n");
      out.write("                                sini</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"margin-top: 2rem; text-align: center; color: var(--text-muted); font-size: 0.85rem;\">\r\n");
      out.write("                &copy; 2025 MoneyMate Financial System\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
